from pyspark import SparkContext, SparkConf, SparkFiles
from pyspark.sql import SQLContext, Row
import ConfigParser as configparser
from subprocess import Popen, PIPE
from datetime import datetime
from vina_utils import get_directory_complex_pdb_analysis, get_files_pdb, get_name_model_pdb, get_ligand_from_receptor_ligand_model, get_separator_filename_mode, get_directory_pdb_analysis, loading_pdb_2_list, get_name_receptor_pdb, get_files_pdb_filter
import os, sys
from os_util import preparing_path
from gromacs_utils import get_value_from_xvg_sasa
from pdb_io import replace_chain_atom_line

def sorting_buried_area(sc, buried_areaRDD):
	sqlCtx = SQLContext(sc)
	buried_areaRDD = sc.parallelize(buried_areaRDD)
	buried_areaRDD = buried_areaRDD.map(lambda p: Row(receptor=str(p[0]), ligand=str(p[1]), model=int(p[2]),sasa_lig_min=float(p[3]), sasa_lig_pose=float(p[4]), sasa_lig_complex=float(p[5]), buried_lig_rec_perc=float(p[6]), buried_lig_lig_perc=float(p[7]) ) )
	buried_area_table = sqlCtx.createDataFrame(buried_areaRDD)	
	buried_area_table.registerTempTable("buried_area")

	buried_area_sorted_by_lig_rec_perc = sqlCtx.sql("SELECT * FROM buried_area ORDER BY buried_lig_lig_perc ") 
	return buried_area_sorted_by_lig_rec_perc

def save_receptor_buried_area(path_file_buried_area, buried_area_sorted_by_lig_rec_perc):	
	f_buried_area = open(path_file_buried_area,"w")
	for area in buried_area_sorted_by_lig_rec_perc:		
		splited_line = area[0].split("_-_")
		aux_recep = splited_line[0]
		aux_lig = str(splited_line[1])		
		#preparing receptor
		receptor = str(str(aux_recep).replace("compl_", " ")).strip()
		#preparing ligand
		splited_aux_lig = str(aux_lig).split(get_separator_filename_mode())
		ligand = splited_aux_lig[0]
		model = splited_aux_lig[1]
		sasa_lig_min = "{:.4f}".format(area[1])
		sasa_lig_pose = "{:.4f}".format(area[2])
		sasa_lig_complex = "{:.4f}".format(area[3])
		buried_lig_rec_perc = "{:.4f}".format(area[4])
		buried_lig_lig_perc = "{:.4f}".format(area[5])
		line = receptor+"\t"+ligand+"\t"+model+"\t"+str(sasa_lig_min)+"\t"+str(sasa_lig_pose)+"\t"+str(sasa_lig_complex)+"\t"+str(buried_lig_rec_perc)+"\t"+str(buried_lig_lig_perc)+"\n"
		f_buried_area.write(line)	
	f_buried_area.close()

def save_buried_area(path_file_buried_area, buried_area_sorted_by_lig_rec_perc):	
	f_buried_area = open(path_file_buried_area,"w")
	for area in buried_area_sorted_by_lig_rec_perc:
		receptor = area[0]
		ligand = area[1]
		model = area[2]
		sasa_lig_min = "{:.4f}".format(area[3])
		sasa_lig_pose = "{:.4f}".format(area[4])
		sasa_lig_complex = "{:.4f}".format(area[5])
		buried_lig_rec_perc = "{:.4f}".format(area[6])
		buried_lig_lig_perc = "{:.4f}".format(area[7])
		line = receptor+"\t"+ligand+"\t"+str(model)+"\t"+str(sasa_lig_min)+"\t"+str(sasa_lig_pose)+"\t"+str(sasa_lig_complex)+"\t"+str(buried_lig_rec_perc)+"\t"+str(buried_lig_lig_perc)+"\n"
		f_buried_area.write(line)	
	f_buried_area.close()

def loading_lines_from_area_files(line):
	line_splited = str(line).split()
	line_ret = ( str(line_splited[0]),str(line_splited[1]), int(line_splited[2]), float(line_splited[3]), float(line_splited[4]), float(line_splited[5]), float(line_splited[6]), float(line_splited[7]) )	
	return line_ret

def get_files_area(mypath):
	only_mol2_file = []
	for root, dirs, files in os.walk(mypath):
		for file in files:
			if file.endswith(".area"):
				f_path = os.path.join(root,file)
				only_mol2_file.append(f_path)			
	return only_mol2_file

def save_log(finish_time, start_time):
	log_file_name = 'vs_buried_areas.log'
	current_path = os.getcwd()
	path_file = os.path.join(current_path, log_file_name)
	log_file = open(path_file, 'w')

	diff_time = finish_time - start_time
	msg = 'Starting ' + str(start_time) +'\n'
	log_file.write(msg)
	msg = 'Finishing ' + str(finish_time) +'\n'
	log_file.write(msg)
	msg = 'Time Execution (seconds): ' + str(diff_time.total_seconds()) +'\n'
	log_file.write(msg)

def main():
	
	config = configparser.ConfigParser()
	config.read('config.ini')

	#Path for Gromacs project
	gromacs_path = preparing_path(config.get('DRUGDESIGN', 'gromacs_path'))
	#Path where PDB ligand are - They are NOT participated in docking
	pdb_ligand_path = config.get('DEFAULT', 'pdb_ligand_path')
	#Path that contains all files for analysis
	path_analysis = config.get('DEFAULT', 'path_analysis')	
	#Path where all pdb receptor are
	path_receptor_pdb = config.get('DEFAULT', 'pdb_path')	
	#Path for saving pdb files of models generated by VS
	path_analysis_pdb = get_directory_pdb_analysis(path_analysis)
	
	# Create SPARK config
	maxResultSize = str(config.get('SPARK', 'maxResultSize'))
	conf = (SparkConf().set("spark.driver.maxResultSize", maxResultSize))

	# Create context
	sc = SparkContext(conf=conf)

	#Adding Python Source file
	#Path for drugdesign project
	path_spark_drugdesign = config.get('DRUGDESIGN', 'path_spark_drugdesign')	
	sc.addPyFile(os.path.join(path_spark_drugdesign,"vina_utils.py"))
	sc.addPyFile(os.path.join(path_spark_drugdesign,"os_util.py"))
	sc.addPyFile(os.path.join(path_spark_drugdesign,"gromacs_utils.py"))
	sc.addPyFile(os.path.join(path_spark_drugdesign,"pdb_io.py"))

	#Adding bash scripts
	sc.addFile(os.path.join(path_spark_drugdesign,"make_ndx.sh"))

	#Parameters form command line
	#Indicates probe. Example: 0.14
	probe = float(sys.argv[1])
	#Indicates ndots. Example: 24
	ndots = int(sys.argv[2])

	#Broadcast
	path_analysis_pdb_complex_b = sc.broadcast(path_analysis_pdb)
	gromacs_path = sc.broadcast(gromacs_path)	 
	pdb_ligand_path = sc.broadcast(pdb_ligand_path)
	probe = sc.broadcast(probe)
	ndots = sc.broadcast(ndots)

	start_time = datetime.now()

	os.environ["GMX_MAXBACKUP"]="-1"

	#Loading all PDB receptor files into memory
	list_all_pdb_receptor_files_path = []
	all_receptor_for_complex = get_files_pdb(path_receptor_pdb)
	for receptor in all_receptor_for_complex:
		list_all_pdb_receptor_files_path.append(loading_pdb_2_list(receptor))

	#Computing Buried areas	
	for pdb_receptor_files in list_all_pdb_receptor_files_path:
		#Getting receptor name by fully path
		base_file_name_receptor = get_name_receptor_pdb(str(pdb_receptor_files[0]))
		#PDB file loaded into memory is sent by broadcast
		pdb_file_receptor = pdb_receptor_files[1]
		pdb_file_receptor = sc.broadcast(pdb_file_receptor)
		#Loading PDB model files based on receptor into memory
		all_model_for_complex = get_files_pdb_filter(path_analysis_pdb,base_file_name_receptor)
		all_model_for_complexRDD = sc.parallelize(all_model_for_complex)
		all_model_filesRDD = all_model_for_complexRDD.map(loading_pdb_2_list).collect()
# ********** Starting function **********************************************************			
		def compute_buried_area(pdb_complex):
			chZ = "chZ"
			buried_lig_rec_perc = -1
			buried_lig_lig_perc = -1
			base_name = get_name_model_pdb(pdb_complex)		
			ligand_name = get_ligand_from_receptor_ligand_model(base_name)
			f_pdb_ligand_no_docking = os.path.join(pdb_ligand_path.value,ligand_name+".pdb")		
			f_ndx = os.path.join(path_analysis_pdb_complex_b.value,base_name+".ndx")
			f_temp_lig_pose = os.path.join(path_analysis_pdb_complex_b.value,"lig_pose_"+base_name+".xvg")
			f_temp_lig_complex = os.path.join(path_analysis_pdb_complex_b.value,"lig_compl_"+base_name+".xvg")
			f_temp_lig_min = os.path.join(path_analysis_pdb_complex_b.value,"lig_min_"+base_name+".xvg")
			# Makes the index file with the ligand (chain z) and the rest (non chain z)
			script_make_ndx = SparkFiles.get("make_ndx.sh") #Getting bash script that was copied by addFile command
			command = script_make_ndx + " " + gromacs_path.value + " "+ pdb_complex + " "+ f_ndx	
			process = Popen(command,shell=True, stdout=PIPE, stderr=PIPE)
			stdout, stderr = process.communicate()	
			# SASA of the isolated ligand in the pose conformation		
			command = gromacs_path.value +"gmx sasa -f "+pdb_complex+" -s "+pdb_complex+" -n "+f_ndx+" -o "+f_temp_lig_pose+" -surface "+ chZ +" -output " + chZ +" -nopbc -noprot -probe "+ str(probe.value) +" -ndots "+ str(ndots.value)+" -xvg none "
			process = Popen(command,shell=True, stdout=PIPE, stderr=PIPE)
			stdout, stderr = process.communicate()
			# SASA of the complexed ligand in the pose conformation
			command = gromacs_path.value +"gmx sasa -f "+pdb_complex+" -s "+pdb_complex+" -n "+f_ndx+" -o "+f_temp_lig_complex+" -surface "+ "System" +" -output " + chZ +" -nopbc -noprot -probe "+ str(probe.value) +" -ndots "+ str(ndots.value)+" -xvg none "
			process = Popen(command,shell=True, stdout=PIPE, stderr=PIPE)
			stdout, stderr = process.communicate()			
			# SASA of the isolated ligand in its energy-minimized conformation
			command = gromacs_path.value +"gmx sasa -f "+f_pdb_ligand_no_docking+" -s "+f_pdb_ligand_no_docking+" -o "+f_temp_lig_min+" -surface "+ "System" +" -output " + "System" +" -nopbc -noprot -probe "+ str(probe.value) +" -ndots "+ str(ndots.value)+" -xvg none "
			process = Popen(command,shell=True, stdout=PIPE, stderr=PIPE)
			stdout, stderr = process.communicate()
			#Getting values from xvg files
			sasa_lig_min = get_value_from_xvg_sasa(f_temp_lig_min)
			sasa_lig_pose  = get_value_from_xvg_sasa(f_temp_lig_pose)
			sasa_lig_complex  = get_value_from_xvg_sasa(f_temp_lig_complex)
			#Computing buried areas
			buried_lig_rec_perc = (sasa_lig_pose - sasa_lig_complex) / sasa_lig_pose
			buried_lig_lig_perc = (sasa_lig_min - sasa_lig_pose) / sasa_lig_min 
			#Generating result - See column sorting because resultaed file will be created based on this sorting
			returned_list = (base_name, sasa_lig_min, sasa_lig_pose, sasa_lig_complex, buried_lig_rec_perc, buried_lig_lig_perc)
			#Deleting files
			os.remove(f_ndx)
			os.remove(f_temp_lig_complex)
			os.remove(f_temp_lig_pose)
			os.remove(f_temp_lig_min)
			return returned_list
# ********** Finish function **********************************************************					

# ********** Starting function **********************************************************		
		def save_model_receptor(list_receptor_model_file):
			receptor_file = pdb_file_receptor.value #Obtained from broadcast
			model_file = list_receptor_model_file[0]			
			full_path_for_save_complex = list_receptor_model_file[1]
			#Open file for writting the complex
			f_compl = open(full_path_for_save_complex, "w")
			#Insert lines of receptor
			for item in  receptor_file:
				f_compl.write(item)
			#Insert lines of model and insert Z chain
			for item in model_file:
				item = replace_chain_atom_line(item,"d","z")
				f_compl.write(item)
			f_compl.close()
# ********** Finish function **********************************************************					

# ********** Starting function **********************************************************		
		def build_list_model_for_complex(model):
			full_path_model = model[0]
			model_file = model[1]
			path_pdb_complex = path_analysis_pdb_complex_b.value #Obtained from broadcast
			#Building complex file based on model file name
			base_name_model = get_name_model_pdb(full_path_model)
			complex_name = "compl_"+base_name_model+".pdb"
			full_path_for_save_complex = os.path.join(path_pdb_complex,complex_name)
			list_receptor_model_file = (model_file, full_path_for_save_complex)			
			save_model_receptor(list_receptor_model_file)
			list_ret = compute_buried_area(full_path_for_save_complex)
			os.remove(full_path_for_save_complex)
			return list_ret
# ********** Finish function **********************************************************					
		
		all_model_filesRDD = sc.parallelize(all_model_filesRDD)
		all_model_filesRDD = all_model_filesRDD.map(build_list_model_for_complex).collect()		
		#Saving buried area of receptor
		full_area_file  = os.path.join(path_analysis,base_file_name_receptor+".area")		
		save_receptor_buried_area(full_area_file, all_model_filesRDD)

	#Loading all area file 
	all_area_file = os.path.join(path_analysis,"*.area")		
	buried_areaRDD = sc.textFile(all_area_file).map(loading_lines_from_area_files).collect()

	#Sorting by buried_lig_rec_perc column
	buried_area_sorted_by_lig_rec_perc = sorting_buried_area(sc, buried_areaRDD)
	buried_area_sorted_by_lig_rec_perc = buried_area_sorted_by_lig_rec_perc.map(lambda p: (p.receptor, p.ligand, p.model, p.sasa_lig_min, p.sasa_lig_pose, p.sasa_lig_complex, p.buried_lig_rec_perc, p.buried_lig_lig_perc) ).collect()

	#Saving buried area file
	path_file_buried_area = os.path.join(path_analysis, "buried_area.txt")
	save_buried_area(path_file_buried_area, buried_area_sorted_by_lig_rec_perc)	

	#Removing all area files
	all_area_files = get_files_area(path_analysis)
	for area_file in all_area_files:
		os.remove(area_file)

	finish_time = datetime.now()

	save_log(finish_time, start_time)

main()